services:
  user-service:
    build:
      context: ./server/user-service
    ports:
      - "5001:5001"
      - "50051:50051"  # gRPC port for user-service
    image: csc3104-user-service:latest
    networks:
      - app-network

  booking-service:
    build:
      context: ./server/booking-service
    ports:
      - "5002:5002"
      - "50052:50052"  # gRPC port for booking-service
    image: csc3104-booking-service:latest
    networks:
      - app-network

  occupancy-service:
    build:
      context: ./server/occupancy-service
    ports:
      - "5003:5003"    # HTTP port for occupancy-service
      - "50053:50053"  # gRPC port for occupancy-service
      - "8080:8080"    # WebSocket port for real-time updates
    image: csc3104-occupancy-service:latest
    networks:
      - app-network

  # Client service to serve the frontend in development mode
  client:
    build:
      context: ./client/gym-booking  # Path to the Dockerfile for the client
    command: npm start
    ports:
      - "80:3000"  # Map host port 80 to container port 3000
    networks:
      - app-network
    volumes:
      - ./client/gym-booking:/app  # Enable hot reloading by mapping local files

networks:
  app-network:
    driver: bridge
