services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    networks:
      - mqtt-network
    volumes:
      - ./mosquitto_config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "checking"]
      interval: 10s
      timeout: 5s
      retries: 5

  equipment-tracking-service:
    build:
      context: ./server/equipment-tracking-service
    container_name: equipment-tracking-service
    depends_on:
      mqtt-broker:
        condition: service_healthy
    environment:
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge

volumes:
  mosquitto_data:
