# booking-service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: felixzzh/csc3104-team25-booking:latest
        ports:
        - containerPort: 5002 # HTTP Port
        - containerPort: 50052 # gRPC Port

---
# booking-service ClusterIP service for internal gRPC communication
apiVersion: v1
kind: Service
metadata:
  name: booking-service-grpc
spec:
  selector:
    app: booking-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052

---
# booking-service NodePort service for external HTTP communication
apiVersion: v1
kind: Service
metadata:
  name: booking-service-http
spec:
  selector:
    app: booking-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: LoadBalancer
