# booking-service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: felixzzh/csc3104-team25-booking:latest
        ports:
        - containerPort: 5002 # HTTP Port
        - containerPort: 50052 # gRPC Port
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      nodeSelector:
        role: booking

---
# booking-service ClusterIP service for internal gRPC communication
apiVersion: v1
kind: Service
metadata:
  name: booking-service-grpc
spec:
  selector:
    app: booking-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052

---
# booking-service NodePort service for external HTTP communication
apiVersion: v1
kind: Service
metadata:
  name: booking-service-http
spec:
  selector:
    app: booking-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booking-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
