# occupancy-service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: occupancy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: occupancy-service
  template:
    metadata:
      labels:
        app: occupancy-service
    spec:
      containers:
      - name: occupancy-service
        image: felixzzh/csc3104-team25-occupancy:latest
        ports:
        - containerPort: 5003 # HTTP Port
        - containerPort: 50053 # gRPC Port

---
# occupancy-service ClusterIP service for internal gRPC communication
apiVersion: v1
kind: Service
metadata:
  name: occupancy-service-grpc
spec:
  selector:
    app: occupancy-service
  ports:
  - protocol: TCP
    port: 50053
    targetPort: 50053

---
# occupancy-service NodePort service for external HTTP communication
apiVersion: v1
kind: Service
metadata:
  name: occupancy-service-http
spec:
  selector:
    app: occupancy-service
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: LoadBalancer
