# occupancy-service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: occupancy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: occupancy-service
  template:
    metadata:
      labels:
        app: occupancy-service
    spec:
      containers:
      - name: occupancy-service
        image: felixzzh/csc3104-team25-occupancy:latest
        ports:
        - containerPort: 5003 # HTTP Port
        - containerPort: 50053 # gRPC Port
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - occupancy-service
              topologyKey: "kubernetes.io/hostname"

---
# occupancy-service ClusterIP service for internal gRPC communication
apiVersion: v1
kind: Service
metadata:
  name: occupancy-service-grpc
spec:
  selector:
    app: occupancy-service
  ports:
  - protocol: TCP
    port: 50053
    targetPort: 50053

---
# occupancy-service NodePort service for external HTTP communication
apiVersion: v1
kind: Service
metadata:
  name: occupancy-service-http
spec:
  selector:
    app: occupancy-service
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: occupancy-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: occupancy-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50