# Use a lightweight Node.js base image
FROM node:lts-alpine

# Set environment variable to development
ENV NODE_ENV=development

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to install dependencies
COPY ["package.json", "package-lock.json*", "./"]

# Install both dependencies and dev dependencies
RUN npm install --silent

# Copy the rest of the application code into the container
COPY . .

# Install nodemon for hot reloading in development
RUN npm install -g nodemon

# Expose the port the app runs on
EXPOSE 50000

# Use nodemon to automatically restart the app on code changes
CMD ["nodemon", "server.js"]
